services:
  pedidos:
    build: .
    tty: true
    stdin_open: true
    restart: unless-stopped
    container_name: pedidos
    ports:
      - "${APPPORT}:80/tcp"
    environment:
      APPPORT: "80"
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG}"
      APP_URL: "${APP_URL}"
      MASTER_KEY: "${MASTER_KEY}"
      APP_LOCALE: "${APP_LOCALE}"
      APP_FALLBACK_LOCALE: "${APP_FALLBACK_LOCALE}"
      APP_FAKER_LOCALE: "${APP_FAKER_LOCALE}"
      APP_MAINTENANCE_DRIVER: "${APP_MAINTENANCE_DRIVER}"
      APP_MAINTENANCE_STORE: "${APP_MAINTENANCE_STORE}"
      PHP_CLI_SERVER_WORKERS: "${PHP_CLI_SERVER_WORKERS}"
      BCRYPT_ROUNDS: "${BCRYPT_ROUNDS}"
      LOG_CHANNEL: "${LOG_CHANNEL}"
      LOG_STACK: "${LOG_STACK}"
      LOG_DEPRECATIONS_CHANNEL: "${LOG_DEPRECATIONS_CHANNEL}"
      LOG_LEVEL: "${LOG_LEVEL}"
      DB_CONNECTION: "${DB_CONNECTION}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      SESSION_DRIVER: "${SESSION_DRIVER}"
      SESSION_LIFETIME: "${SESSION_LIFETIME}"
      SESSION_ENCRYPT: "${SESSION_ENCRYPT}"
      SESSION_PATH: "${SESSION_PATH}"
      SESSION_DOMAIN: "${SESSION_DOMAIN}"
      BROADCAST_CONNECTION: "${BROADCAST_CONNECTION}"
      FILESYSTEM_DISK: "${FILESYSTEM_DISK}"
      QUEUE_CONNECTION: "${QUEUE_CONNECTION}"
      CACHE_STORE: "${CACHE_STORE}"
      CACHE_PREFIX: "${CACHE_PREFIX}"
      MEMCACHED_HOST: "${MEMCACHED_HOST}"
      REDIS_CLIENT: "${REDIS_CLIENT}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT}"
      MAIL_MAILER: "${MAIL_MAILER}"
      MAIL_SCHEME: "${MAIL_SCHEME}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${APP_NAME}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_BUCKET: "${AWS_BUCKET}"
      AWS_USE_PATH_STYLE_ENDPOINT: "${AWS_USE_PATH_STYLE_ENDPOINT}"
      VITE_APP_NAME: "${APP_NAME}"
