[dependencies]
"php/php-64" = "=8.3.2102"
 
[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php-64:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/app/webroot", "-S", "localhost:8080"]